[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.mako]
input_path = './templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.wezterm]
input_path  = "./templates/wezterm.toml"
output_path = "~/.config/wezterm/colors/theme.toml"

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
#post_hook = 'if [ "{{mode}}" = "dark" ]; then gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Dark"; else gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Light"; fi'
post_hook = "theme-gtk3 -m {{mode}}"

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
#post_hook = 'if [ "{{mode}}" = "dark" ]; then gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"; else gsettings set org.gnome.desktop.interface color-scheme "prefer-light"; fi'
post_hook = "theme-gtk4 -m {{mode}}"

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.neovim]
input_path = './templates/template.lua'
output_path = '~/.config/nvim/lua/plugins/colorscheme.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.equibop]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/equibop/themes/midnight-discord.css'

[templates.Obisidan]
input_path = './templates/obsidian.json'
output_path = '~/.local/share/obsidian/vault/.obsidian/plugins/obsidian-style-settings/data.json'
post_hook='''if [ "{{mode}}" = "dark" ]; then
  sed -i -E 's/("accentColor": ")[^"]*(")/\1{{colors.surface.default.hex}}\2/g; s/("theme": ")[^"]*(")/\1obsidian\2/g' ~/.local/share/obsidian/vault/.obsidian/appearance.json
else
  sed -i -E 's/("accentColor": ")[^"]*(")/\1{{colors.surface.default.hex}}\2/g; s/("theme": ")[^"]*(")/\1moonstone\2/g' ~/.local/share/obsidian/vault/.obsidian/appearance.json
fi'''
#post_hook = '''sed -E -i 's/("accentColor": ")[^"]*(")/\\1{{colors.surface.default.hex}}\\2/g' ~/.local/share/obsidian/vault/.obsidian/appearance.json'''

[templates.vscode]
input_path = './templates/vscode.json'
output_path = '~/.local/share/vscode/user-data/User/settings.json'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'
